steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.sync
      - -t
      - gcr.io/$PROJECT_ID/gesa-supabase-sync
      - .
images:
  - gcr.io/$PROJECT_ID/gesa-supabase-sync
