export const PRA_EXISTING_TABANAN_DATA: Record<string, Record<string, string[]>> = {
  Tabanan: {
    "DELOD PEKEN": ["Delod rurung", "Gerokgak gede", "Gerokgak Tengah", "Sakenan Belodan", "Sakenan Baleran", "Taman Sari", "Pangkung"],
    "DAJAN PEKEN": ["Kamasan", "Malkangin", "Pasekan", "Banjar Lebah", "Jambe Baleran", "Pasekan Baleran", "Pande", "Dangin Carik"],
    "DAUH PEKEN": ["Dauh Pala", "Dukuh", "Jambe Belodan", "Tegal Baleran", "Tegal Belodan", "Tunggalsari"],
    DENBANTAS: ["Denbantas", "Bakisan", "Dukuh Buahan", "Celagi", "Tuakilang Baleran", "Tuakilang Belodan"],
    BONGAN: ["B Pala", "B Gede", "B Tengah", "B Lebah", "B Jawa Kangin", "B Jawa Kawan", "B Kauh Kaja", "B Kauh Kelod", "Wanasara Kaja", "Wanasara Kelod", "Bedha"],
    SUBAMIA: ["SUBAMIA AMBAL-AMBAL", "SUBAMIA DEN CARIK", "SUBAMIA BALE AGUNG", "SUBAMIA KELONG"],
    GUBUG: ["GUBUG BALERAN", "GUBUG BELODAN", "PANDE", "BATU SANGIAN", "TAMAN", "TONJA", "PENGAYEHAN", "CURAH"],
    WANASARI: ["WANASARI BALERAN", "WANASARI TENGAH", "WANASARI BELODAN", "ABIANLALANG", "PERIYUKTI"],
    BUAHAN: ["B Utara", "B Tengah", "B Selatan"],
    SUDIMARA: ["Yeh Gangga", "Sudimara Kelod", "Sudimara Kaja", "Cengolo", "Kalanganyar Kangin", "Kalanganyar", "Jelae", "Sakeh", "Celuk Kanginan", "Katimemes"],
    SESANDAN: ["Sekartaji", "Sandan Pondok", "Sandan Dauh Yeh Baleran", "Sandan Dauh Yeh", "Sandan Tegeh", "Sandan Dangin Yeh", "Sandan Lebah"],
    TUNJUK: ["Bungan Kapal", "Legung", "Tunjuk Kaja", "Tunjuk Tengah", "Tunjuk Kelod", "Beng Kaja", "Beng Kelod"],
  },
  Kediri: {
    KEDIRI: ["JAGASATRU", "SEMA", "PUSEH", "PANDE", "DELOD PURI", "PANTI", "DEMUNG"],
    "BANJAR ANYAR": ["BANJAR ANYAR", "TAMAN SARI ANYAR", "TAMAN SEKAR", "TANAH BANG", "SENAPAHAN KELOD", "PEMENANG", "JADIDESA", "JADI BABAKAN", "SANGGULAN", "DAJAN TENTEN", "JADI ANYAR", "SANGGULAN ANYAR", "SENAPAHAN KAJA"],
    ABIANTUWUNG: ["PANGKUNG NYULING", "SURALAGA", "NYANG API", "BALU", "PASEKAN", "ABIANTUWUNG KAJA", "ABIANTUWUNG KELOD", "GANTER", "TAPESAN GANTER", "DAKDAKAN", "KORIPAN KAJA", "KORIPAN KELOD", "TAMAN SURODADI"],
    "PANDAK BANDUNG": ["MALMUNDEH", "MERANGGI", "LAING", "BANDUNG"],
    NYITDAH: ["KEBON", "SENGGUAN", "TEGAL", "TEGAL ANTUGAN", "SUDA", "SUDA KANGINAN", "BABAKAN", "MENGENING"],
    BERABAN: ["ULUNDESA", "GEGELANG", "BATAN BUAH KAJA", "BERABAN", "BATUGAING KAJA", "BATUGAING", "DUKUH", "SINJUANA", "NYANYI"],
    NYAMBU: ["CARIK PADANG", "DUKUH", "KEBAYAN", "MUNDEH", "NYAMBU", "TOH JIWA"],
    BENGKEL: ["BENGKEL BUDUK", "BENGKEL GEDE", "BENGKEL KAWAN", "TELENGIS"],
    BELALANG: ["DANGIN JELINJING", "DAUH RURUNG", "KEBIBIL", "PACUNG", "KEDUNGU"],
    PEJATEN: ["PANGKUNG", "SIMPANGAN", "BADUNG", "PAMESAN", "DUKUH", "PEJATEN", "BALERAN", "DALEM"],
    CEPAKA: ["BATAN DUREN", "CEPAKA", "LALANG PASEK"],
    "PANDAK GEDE": ["BATAN POH", "PANGKUNG", "SABA", "BELATUNG", "PANTI", "TAMAN SARI", "KEBON", "PASTI"],
    "PANGKUNG TIBAH": ["PANGKUNG TIBAH", "PANGKUNG TIBAH BALERAN", "LANGUDU"],
    "KABA-KABA": ["BERINGKIT", "BUADING", "DAUH YEH", "DUALANG", "JUNTAL", "SENGGUAN", "TEGAL KEPUH", "PILISAN", "DANGIN UMA", "GADUH"],
    BUWIT: ["KELAKAHAN", "DELOD SEMA", "BUWIT", "DELOD UMA"],
  },
  Baturiti: {
    PEREAN: ["Perean", "Puseh", "Bunyuh", "Penyucuk"],
    LUWUS: ["Luwus", "Belah", "Poyan", "Punjuan", "Palian", "Mandul"],
    APUAN: ["Apuan", "Jelantik", "Tinungan", "Kambangan"],
    ANGSERI: ["Angseri", "Angseri Kelod", "Tegeh", "Munduk Lumbang"],
    BANGLI: ["Gunung Kangin", "Bangli", "Umopoh", "Apit Yeh", "Titigalar", "Munduk Andong", "Sandan"],
    BATURITI: ["Abang", "Pekarangan", "Baturiti Kaja", "Baturiti", "Baturiti Kelod", "Pacung", "Bangah", "Abian Luwang"],
    ANTAPAN: ["Antapan", "Talangpati", "Tohjiwa", "Mayungan Anyar", "Mayungan Let", "Gelogor"],
    "CANDI KUNING": ["Kembangmerta", "Candikuning I", "Candikuning II", "Bukitcatu", "Pemuteran", "Batusesa"],
    MEKARSARI: ["Mojan", "Peneng", "Tundak", "Temacun", "Sekargula", "Kerobokan"],
    BATUNYA: ["Batunya", "Juwuklegi", "Taman Tanda", "Abing"],
    "PEREAN TENGAH": ["Kukub", "Tuka", "Berteh", "Selat"],
    "PEREAN KANGIN": ["Beluangan", "Banjar Anyar", "Basangbe", "Piun", "Leba"],
  },
  Penebel: {
    REJASA: ["PACUT", "REJASA KELOD", "REJASA KAJA", "KELEMBANG"],
    JEGU: ["BR DINAS SIGARAN", "BR DINAS CEPAG", "BR DINAS JEGU BALEAGUNG", "BR DINAS JEGU PANDE", "BR DINAS JEGU TENGAH", "BR DINAS JEGU TEGAL", "BR DINAS BENDUL", "BR DINAS NGIS KAJA", "BR DINAS NGIS KELOD"],
    "RIANG GEDE": ["DARMA KAJA", "DARMA TENGAH", "DARMA KELOD", "RIANG KAJA", "RIANG TENGAH", "RIANG KELOD", "RIANG DELODSEMA", "RIANG ANCUT", "RIANG DELODSEMA GEDE"],
    BURUAN: ["BURUAN KAJA", "BURUAN TENGAH", "BURUAN KELOD", "BENANA KAJA", "BENANA KELOD"],
    BIAUNG: ["PUMAHAN", "PEMANIS", "PEMANIS KELOD", "CACAB JANGKAHAN", "BIAUNG KAJA", "BIAUNG TENGAH", "BIAUNG KELOD"],
    PITRA: ["SERASON", "POHGENDING KANGIN", "POHGENDING KAWAN", "NYELEKET", "NYULING", "PITRA", "ASAH KAJA", "ASAH KELOD"],
    PENATAHAN: ["MONGAN", "BEDUGUL", "PENATAHAN KAJA", "PENATAHAN KELOD", "KEKERAN", "TEGAYANG"],
    SANGKETAN: ["Br. Dinas Sangketan", "Br. Dinas Puring", "Br. Dinas Anyar", "Br. Dinas Munduk Dawa", "Br. Dinas Pekandelan", "Br. Dinas Bun", "Br. Dinas Bongli"],
    TENGKUDAK: ["Penganggahan", "Denuma", "Tengkudak", "Puluk Puluk", "Tingkihkerep"],
    MENGESTA: ["MENGESTA", "PILING TENGAH", "PILING KANGINAN", "PILING KAWAN", "KEDAMPAL", "BELULANG", "WONGAYABETAN"],
    PENEBEL: ["Banjar Dinas Penebel Kaja", "Banjar Dinas Penebel Kelod", "Banjar Dinas Karadan", "Banjar Dinas Dukuh", "Banjar Dinas Kupang", "Banjar Dinas Ubung", "Banjar Dinas Sunantaya Kaja", "Banjar Dinas Sunantaya Kelod", "Banjar Dinas Gunung"],
    BABAHAN: ["BABAHAN KAWAN", "BABAHAN TENGAH", "BABAHAN KANGINAN", "DADIA", "BOLANGAN", "UTU"],
    SENGANAN: ["BR DINAS BUGBUGAN ANYAR", "BR DINAS BUGBUGAN KAJA", "BR DINAS BUGBUGAN KELOD", "BR DINAS BUGBUGAN SARI", "BR DINAS KERIDAN", "BR DINAS PACUNG", "BR DINAS PAGI", "BR DINAS SENGANAN KANGINAN", "BR DINAS SENGANAN KAWAN KAJA", "BR DINAS SENGANAN KAWAN KELOD", "BR DINAS SOKA KANGINAN", "BR DINAS SOKA KAWAN"],
    JATILUWIH: ["Kesambi", "Kesambahan Kaja", "Kesambahan Kelod", "Jatiluwih Kawan", "Jatiluwih Kangin", "Gunungsari Desa", "Gunungsari Umakayu", "Gunungsari Kelod"],
    "WONGAYA GEDE": ["WONGAYA KAJA", "WONGAYA KELOD", "WONGAYA KANGIN", "WONGAYA BENDUL", "KELONCING", "BATUKAMBING", "BENGKEL", "AMPLAS", "SANDAN"],
    TAJEN: ["BR DINAS TAJEN DAUH YEH", "BR DINAS TAJEN JEROAN", "BR DINAS TAJEN SEDAHAN", "BR DINAS TAJEN PANDE", "BR DINAS TAJEN KUTABALI", "BR DINAS CEPIK", "BR DINAS CEPIK KELOD"],
    TEGALINGGAH: ["TEGALLINGGAH KAJA", "TEGALLINGGAH KELOD", "TEGALLINGGAH PONDOK", "TATAG"],
    PESAGI: ["CANGKUP", "PESAGI", "TEMUKUAYA", "MUNDUK JUWET", "KUUMKELADI", "PEGUBUGAN KAUH", "PEGUBUGAN KANGIN", "TEGAL SEKA"],
  },
  Pupuan: {
    BELIMBING: ["BELIMBING DESA", "DUREN TALUH", "SURADADI", "BENITI", "BELANTIBAH", "BELIMBING ANYAR", "BELIMBING TEGAL", "PEMUDUNGAN"],
    SANDA: ["SANDA", "PAKA", "SEKAR SANDAT"],
    BATUNGSEL: ["BATUNGSEL KAJA", "BATUNGSEL KELOD", "PEMPATAN"],
    "KEBON PADANGAN": ["KEBON KAJA", "KEBON KELOD", "BALE TIMBANG", "GALI UKIR KAJA", "GALI UKIR KELOD"],
    PUJUNGAN: ["PUSPASARI", "MARGASARI", "MERTASARI", "TAMANSARI", "MEKARSARI", "TIBU DALEM"],
    PUPUAN: ["PUPUAN", "KUBU", "KAYU PURING", "KAYU PADI", "SEMOJA"],
    BANTIRAN: ["BANTIRAN", "AMBANG", "ASAH", "TEJA BUKIT", "BANTIRAN KELOD", "TEMUSARI", "PALISAN", "SASAN", "SELEKSEK"],
    PAJAHAN: ["PAJAHAN", "KELAU", "DUREN MINCID", "TANGIS", "TANAH SARI", "BANYUSARI"],
    "MUNDUK TEMU": ["MUNDUK TEMU KAJA", "MUNDUK TEMU KELOD", "ANGGASARI KAJA", "ANGGASARI KELOD", "KEBON JERO KANGIN", "KEBON JERO KAUH"],
    BELATUNGAN: ["MUNDUK NGANDANG", "MUNDUK GAWANG", "ANTAP GAWANG", "DAJAN CEKING", "DELOD CEKING", "YEH SIBUH"],
    PADANGAN: ["PADANGAN KAJA", "PADANGAN KELOD", "PADANGAN KAWAN", "PADANGAN KANGIN", "DAUH TUKAD"],
    "JELIJIH PUNGGANG": ["PUNGGANG", "JELIJIH", "JELIJIH KELOD"],
    "KARYA SARI": ["KARYA SARI", "ASAH TEGEH"],
    SAI: ["SAI", "YEH BUSBUS", "YEH TUA", "GAMBUK"],
  },
  Marga: {
    TUA: ["TUA", "CAU", "BAYAN"],
    BARU: ["BARU", "RADEN", "PINGE", "SUSUT"],
    PETIGA: ["SEMINGAN", "BELABAN", "PETIGA KANGIN"],
    GELUNTUNG: ["UMABALI", "GELUNTUNG KAJA", "GELUNTUNG KAJELODA", "KIKIK"],
    MARGA: ["LEBAH", "BASA", "BENG", "TEMBAU"],
    "MARGA DAJAN PURI": ["BANJAR DINAS ANYAR", "BANJAR DINAS BUGBUGAN", "BANJAR DINAS TENGAH", "TENGAH SEMETON"],
    "MARGA DAUH PURI": ["OLE", "KELACI"],
    KUWUM: ["KUWUM TEGALLINGGAH", "KUWUM MAMBAL", "KUWWUM ANYAR", "KUWUM ANCAK", "KUWUM ANCAK BUA"],
    BATANNYUH: ["BATANNYUH KAJA", "BATANNYUH KELOD", "UMADIWANG KANGIN", "UMADIWANG KAWAN"],
    "PEKEN BELAYU": ["PEKANDELAN", "TENGAH", "PEKEN", "GUNUNG SIKU", "UMABIAN"],
    "BERINGKIT BELAYU": ["BERINGKIT", "JEBAUD", "BAJERA BELAYU", "BAJERA PEGEBEGAN"],
    KUKUH: ["LODALANG", "TENGAH", "MUNGGAL", "DALEM KERTI", "BATANWANI", "TEGAL", "DENUMA", "TATAG"],
    TEGALJADI: ["ADENG", "PENGEMBUNGAN", "TEGAL JADI"],
    "CAU BELAYU": ["CAU BELAYU", "SERIBUPATI", "BABAKAN", "PADANGALING"],
    SELANBAWAK: ["SELANBAWAK KAJA", "SELANBAWAK KELOD", "MANIK GUNUNG", "KEKERAN", "PEKILEN"],
    PAYANGAN: ["BUNUTIN", "KALIBALANG", "PAYANGAN GRESEH", "PAYANGAN KAJA", "PAYANGAN TENGAH", "ALAS TERUNA", "ALAS SANDAN", "PAYANGAN MEDI", "GELAGAH"],
  },
  Kerambitan: {
    KERAMBITAN: ["Br.Dinas Kedampal", "Br.Dinas Pekandelan", "Br.Dinas Wani", "Br.Dinas Wani Kawan", "Br.Dinas Tengah Kawan", "Br.Dinas Tengah", "Br.Dinas Tengah Kangin"],
    KELATING: ["DAUH JALAN", "DANGIN JALAN", "DUKUH", "DANGIN PANGKUNG", "SANGGING", "PANDE"],
    BATURITI: ["Br. Dinas Baturiti Kelod", "Br. Dinas Baturiti Tengah", "Br. Dinas Baturiti Kaja", "Br. Dinas Dukuh Belong", "Br. Dinas Dukuh Gede", "Br. Dinas Munduk Catu"],
    KUKUH: ["SAMSAMAN ALAS", "SAMSAMAN KELOD", "KUKUH KANGIN", "KUKUH KAWAN", "KUKUH KELOD"],
    TISTA: ["Carik", "Dangin Pangkung", "Lebah", "Dauh Pangkung"],
    BELUMBANG: ["LANGAN", "BELUMBANG KAJA", "BELUMBANG TENGAH", "BELUMBANG KELOD", "YEH MALET KAJA", "YEH MALET KELOD", "TIBUPOH", "BELONG"],
    PENARUKAN: ["Penarukan Kaja", "Penarukan Tengah Kaja", "Penarukan Tengah", "Penarukan Kelod", "Penarukan Bntas"],
    "PKG KARUNG": ["SELINGSING KAJA", "SELINGSING KELOD", "PANGKUNGKARUNG KANGIN", "PANGKUNGKARUNG KAWAN", "SERONGGA PONDOK", "SERONGGA GEDE", "SERONGGA KEMENUH"],
    "SEMBUNG GEDE": ["SARASIDI", "PAYUK BANGKAH", "SEMBUNG GEDE", "SEMBUNG GEDE KELOD", "SEMBUNG MERANGGI", "MANDUNG", "MANDUNG KANGIN", "SEMBUNG KUMPI", "BATUAJI KAWAN KELOD", "BATUAJI KAWAN KAJA"],
    MELILING: ["Bangkiang Mayung", "Meliling Kawan", "Meliling Kangin", "Jagatamu"],
    TIMPAG: ["Delod Peken", "Dajan Peken", "Beluluk", "Sambian Pondok", "Sambian Tengah", "Telaga Tunjung"],
    BATUAJI: ["Pelem Gede", "Batuaji Kelod", "Batuaji Tengah", "Batuaji Kaja", "Penulisan", "Jangkahan"],
    KESIUT: ["Kesiut Kangin", "Kesiut Tengah Kaja", "Kesiut Tengah Kelod", "Kesiut Kawan Kaja", "Kesiut Kawan Kelod"],
    TIBUBIU: ["Tegal Temu Kaja", "Tegal Temu Kelod", "Tibubiu Kaja", "Tibubiu Kelod", "Pasut"],
    SAMSAM: ["Lumajang", "Samsam II", "Samsam I", "Penyalin", "Kutuh Kelod", "Kutuh Kaja"],
  },
  Selemadeg: {
    SELEMADEG: ["Gamongan", "Singin", "Selemadeg Kaja", "Selemadeg Bale Agung", "Selemadeg Kelod", "Sukawati", "Babakan"],
    WANAGIRI: ["Sawah", "Babakan", "Pajahan", "Wanagiri", "Sarinbuana", "Biyahan"],
    "WANAGIRI KAUH": ["Kebon Anyar", "Kebon Cepaka", "Kebon Tumpalan", "Kebon Bantiran", "Mendek", "Kerta"],
    BAJERA: ["Bajera Kaja", "Bajera Tenah", "Bajera Kelod", "Bajera Jero", "Saraswati", "Bajera Sari"],
    "BAJERA UTARA": ["Kebon", "Lenganan", "Munduk", "Menungul", "Taman Yoga", "Cibukan"],
    BEREMBENG: ["Berembeng", "Gablogan", "Cekik", "Bebali", "Bebali Kelod"],
    SERAMPINGAN: ["Munggu jeroan", "Baleagung Kaba-kaba", "Delod Sema Cemagi", "Jemberana", "Wani", "Waru"],
    "PUPUAN SAWAH": ["Kikian", "Pupuan Sawah", "Laleng", "Cangkup"],
    MANIKYANG: ["Cepaka", "Manikyang", "Apityeh", "Guniang"],
    ANTAP: ["Antap Dajan Telabah", "Antap Dajan Sema", "Antap Delod Sema", "Antap Kelod", "Soka Kaja", "Soka Kelod", "Payan", "Batulumbang", "Bonian"],
  },
  "Selemadeg Barat": {
    "TIYING GADING": ["Banjar Anyar", "Dukuh", "Tiyinggading", "Ampadan", "Antagana Kelod", "Antagana Kaja", "Antagana Kangin"],
    MUNDEH: ["Yeh Kayu", "Pancoran Kelod", "Pancoran", "Nyuhgading", "Pengedan", "Bangal", "Auman Delod Sema", "Auman Dajan Sema"],
    "MUNDEH KAUH": ["Dayang", "Penataran", "Dukuh", "Puncak Sari", "Kedewatan"],
    "MUNDEH KANGIN": ["Mundeh Kangin", "Mundeh Kawan", "Pakuaji", "Pasut", "Cantel", "Gelunggang"],
    ANGKAH: ["Angkah Pondok", "Angkah Gede", "Angkah Tegeh", "Angkah Munduk", "Samsaman Kaja", "Samsaman Kelod", "Margetelu", "Wanayu"],
    LUMBUNG: ["Dajan sema", "delod sema", "anom", "lumbung", "cempaka", "pengereregan kaja", "pengereregan tengah", "pengereregan kelod"],
    "LUMBUNG KAUH": ["Nagasari", "Dauhsiyong", "Tegalkontang", "Yehsilah", "Delodceking"],
    LALANGLINGGAH: ["Lalanglinggah", "Suraberata", "Pengasahan", "Banjar Kutuh", "Desa Anyar", "Daren", "Mekayu", "Beja", "Yeh Bakung", "Bangkiang Jaran", "Bukit Tumpeng"],
    SELABIH: ["Selabih Wanasari", "Selabih Tengah", "Selabih Pangkung Kuning"],
    ANTOSARI: ["Petiles", "Umaseka", "Gulingan", "Tengah", "Delod Rurung", "Dangin Pangkung", "Bade Gede"],
    "BENGKEL SARI": ["Tireman", "Semaja", "Bengkel", "Lbk Suren I", "Lbk Suren II"],
  },
  "Selemadeg Timur": {
    MEGATI: ["SERAMPINGAN KELOD", "SERAMPINGAN KAJA", "MEGATI KELOD", "MEGATI KAJA", "JELIJIH TEGEH", "JELIJIH LEBAH", "JELIJIH PONDOK", "SESANDAN KAUH", "SESANDAN KANGIN"],
    TEGALMENGKEB: ["KELECUNG KELOD", "KELECUNG KAJA", "ALAS", "MUNDUK ULAN", "BRANJINGAN", "BONGAN", "TEGALMENGKEB KAJA", "TEGALMENGKEB TENGAH", "TEGALMENGKEB KELOD"],
    DALANG: ["GEMPINIS KAUH", "GEMPINIS KANGIN", "KETIMA", "DALANG DESA", "DALANG ANYAR", "MUNDUK MALANG"],
    "GUNUNG SALAK": ["APIT YEH", "BANGKIANG SIDEM", "GUNUNG SALAK", "KEMETUG DESA", "KEMETUG KANCIANA"],
    BERABAN: ["TEGES", "GEROMBONG", "BERABAN KANGIN", "BERABAN KAUH", "PONDOK"],
    TANGGUNTITI: ["BATANBUAH", "TEMUKUAYA", "PONDOK MEKAR", "KEBON", "NYAMPUAN", "TANGGUNTITI", "JAKATEBEL"],
    MAMBANG: ["MAMBANG GEDE", "MAMBANG TENGAH", "MAMBANG KAJA", "MAMBANG CELUK KAJA", "MAMBANG CELUK KELOD", "SAMBAT SEE", "DUKUH PULU KAJA", "DUKUH PULU TENGAH", "DUKUH PULU KELOD", "BABAKAN", "ALAS"],
    GADUNGAN: ["IPIL", "WANI", "GADUNGAN DESA", "TEGEH", "SWASTIKA CARIK KANGIN", "MEKARSARI CARIK KAUH", "PONDOK KELOD", "PONDOK KAJA", "PANGKUNG LANGKUAS", "MUNDUK MALANG"],
    "GADUNG SARI": ["MUNDUK PAKEL", "NYATNYATAN", "CEPAKA"],
    BANTAS: ["PUCUK", "BANTAS BALE AGUNG", "BANTAS TENGAH KELOD", "BANTAS TENGAH KAJA", "GELOGOR", "BUNUT PUHUN"],
  },
};
